source : https://mubaris.com/posts/kmeans-clustering/

In [47]:
# Dependencies

# import pandas as pd
import numpy as np
# from sklearn.cluster import KMeans
# from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import MinMaxScaler
# import seaborn as sns
import matplotlib.pyplot as plt
import cv2
from sklearn.cluster import KMeans
import pickle
import glob
from sklearn.neighbors.nearest_centroid import NearestCentroid

Create Sift

In [29]:
img = cv2.imread("image/icon/asus_icon.png")
sift = cv2.xfeatures2d.SIFT_create()

In [30]:
def readPhotosDir(directory):
    listPhotosDir = glob.glob(directory+"/*.png")
    return listPhotosDir

In [31]:
def openPhotos(PhotosDir):
    img = cv2.imread(PhotosDir)
    
    return img

Nyari fitur key point

In [56]:
keypoints_sift, descriptors = sift.detectAndCompute(img, None)

img = cv2.drawKeypoints(img, keypoints_sift, None)
print(descriptors)
# cv2.imshow("Image", img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[10.  0.  0. ...  0.  0.  0.]
 [63. 46.  1. ... 86.  4.  0.]
 [21.  6.  0. ...  0.  0.  0.]
 ...
 [17.  5.  0. ...  2.  3.  2.]
 [12.  1.  0. ...  0.  0.  3.]
 [21.  0.  0. ...  1.  2.  6.]]


In [23]:
def findFeature(img):
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints_sift, descriptors = sift.detectAndCompute(img, None)
    
    return keypoints_sift, descriptors

Coba cek koordinat fiture

In [24]:
# pts = [k.pt for k in keypoints_sift]
# print ('The list of detected keypoints is:', pts)

K Means Clustering

In [25]:
# k_clusters = 3
# results = []
# algorithms = {}

# algorithms['kmeans'] = cluster.KMeans(n_clusters=k_clusters, n_init=200)

In [114]:
# create kmeans object
kmeans = KMeans(n_clusters=4)
# fit kmeans object to data
kmeans.fit(descriptors)
# print location of clusters learned by kmeans object
centroid1 = kmeans.cluster_centers_
# save new clusters for chart
y_km = kmeans.fit_predict(descriptors)
x=centroid1[:,0]
print(x[0])
print(centroid1[:,1])



11.343746
[ 3.812502  23.734697   1.3076897 19.999998 ]


In [79]:
def makeCentroid(descriptors):
    kmeans = KMeans(n_clusters=4)
    kmeans.fit(descriptors)
    centroid = kmeans.cluster_centers_
    x=centroid[:,0]
    y=centroid[:,1]
    
    return x,y

In [80]:
def takePhotoName(photoDir):
    temp = photoDir.split('/')#image/icon/pepsi_icon.png => imaga,icon,pepsi_icon.png
    temp = temp[len(temp)-1].split('_')#pepsi_icon.png => pepsi, icon.png
    return temp[0]

In [122]:
def findFeaturOfListPhoto(listOfDir):
    dictOfPhotoFeature = {}
    coordinate = {}
    
    for photoDir in listOfDir:
        name = takePhotoName(photoDir)
        img = openPhotos(photoDir)
        keypoint, descriptor = findFeature(img)
        x,y = makeCentroid(descriptor)
        coordinate[0]=x
        coordinate[1]=y
        
        dictOfPhotoFeature[name] = coordinate
        
    return dictOfPhotoFeature

In [123]:
directory = "image/icon"

listPhotosDir = readPhotosDir(directory)
# print(listPhotosDir)
dictOfPhotoFeature = findFeaturOfListPhoto(listPhotosDir)

Buat Pickle

In [124]:
file = open('model.pickle','wb')
pickle.dump(dictOfPhotoFeature,file)
file.close()