source : https://mubaris.com/posts/kmeans-clustering/

In [1]:
# Dependencies

# import pandas as pd
import numpy as np
# from sklearn.cluster import KMeans
# from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import MinMaxScaler
# import seaborn as sns
import matplotlib.pyplot as plt
import cv2
from sklearn.cluster import KMeans
import pickle
import glob
from sklearn.neighbors.nearest_centroid import NearestCentroid

Create Sift

In [29]:
img = cv2.imread("image/icon/asus_icon.png")
sift = cv2.xfeatures2d.SIFT_create()

In [8]:
def readPhotosDir(directory):
    listPhotosDir = glob.glob(directory+"/*.*")
    return listPhotosDir

In [3]:
def openPhotos(PhotosDir):
    img = cv2.imread(PhotosDir)
    
    return img

Nyari fitur key point

In [56]:
keypoints_sift, descriptors = sift.detectAndCompute(img, None)

img = cv2.drawKeypoints(img, keypoints_sift, None)
print(descriptors)
# cv2.imshow("Image", img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[10.  0.  0. ...  0.  0.  0.]
 [63. 46.  1. ... 86.  4.  0.]
 [21.  6.  0. ...  0.  0.  0.]
 ...
 [17.  5.  0. ...  2.  3.  2.]
 [12.  1.  0. ...  0.  0.  3.]
 [21.  0.  0. ...  1.  2.  6.]]


In [4]:
def findFeature(img):
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints_sift, descriptors = sift.detectAndCompute(img, None)
    
    return keypoints_sift, descriptors

Coba cek koordinat fiture

In [24]:
# pts = [k.pt for k in keypoints_sift]
# print ('The list of detected keypoints is:', pts)

K Means Clustering

In [25]:
# k_clusters = 3
# results = []
# algorithms = {}

# algorithms['kmeans'] = cluster.KMeans(n_clusters=k_clusters, n_init=200)

In [114]:
# create kmeans object
kmeans = KMeans(n_clusters=4)
# fit kmeans object to data
kmeans.fit(descriptors)
# print location of clusters learned by kmeans object
centroid1 = kmeans.cluster_centers_
# save new clusters for chart
y_km = kmeans.fit_predict(descriptors)
x=centroid1[:,0]
print(x[0])
print(centroid1[:,1])



11.343746
[ 3.812502  23.734697   1.3076897 19.999998 ]


In [5]:
def makeCentroid(descriptors):
    kmeans = KMeans(n_clusters=4)
    kmeans.fit(descriptors)
    centroid = kmeans.cluster_centers_
    x=centroid[:,0]
    y=centroid[:,1]
    
    return x,y

In [6]:
def takePhotoName(photoDir):
    temp = photoDir.split('/')#image/icon/pepsi_icon.png => imaga,icon,pepsi_icon.png
    temp = temp[len(temp)-1].split('_')#pepsi_icon.png => pepsi, icon.png
    return temp[0]

In [40]:
def findFeaturOfListPhoto(listOfDir):
    dictOfPhotoFeature = {}
    
    
    for photoDir in listOfDir:
        name = takePhotoName(photoDir)
        img = openPhotos(photoDir)
        keypoint, descriptor = findFeature(img)
        
#         test
        print(name)
        coordinate = []
        x,y = makeCentroid(descriptor)
        coordinate.append(x)
        coordinate.append(y)
        
        dictOfPhotoFeature[name] = coordinate
        
    return dictOfPhotoFeature

<h1>Proses===</h1>

In [41]:
directory = "image/icon"

listPhotosDir = readPhotosDir(directory)
# print(listPhotosDir)
dictOfPhotoFeature = findFeaturOfListPhoto(listPhotosDir)

bmwm
dell
aqua
rog
renault
oppo
bmw
lenovo
ferrari
lamborghini
hp
toyota
hokben
chevolet
suzuki
samsung
daihatsu
alfaromeo
toshiba
honda
mustang
xiaomi
gokana
ford
mercedes
logitech
pepsi
starbucks
asus
acer


Buat Pickle

In [42]:
file = open('model.pickle','wb')
pickle.dump(dictOfPhotoFeature,file)
file.close()

In [44]:
print(dictOfPhotoFeature['suzuki'])
# print(dictOfPhotoFeature['acer'])

[array([ 1.4583349, 11.916667 , 15.473684 , 17.599998 ], dtype=float32), array([1.5000007, 5.8333344, 3.2631583, 6.6800013], dtype=float32)]
